cf-cli/cf-cli_6.28.0_linux_x86-64.tgz:
  size: 5715491
  object_id: 24341322-c994-409e-5fd9-96008d6c95c7
  sha: 19e7a8f3d1c094fd008704c685d5c4595306b0f5
golang/go1.10.linux-amd64.tar.gz:
  size: 119905205
  object_id: f4cf5125-0c1f-4c5f-4d83-20955a322074
  sha: 693e2dfd99ef2d608b41c450efd9d277bf2a7f2f
jq/jq-linux64-1.5:
  size: 3027945
  object_id: 805e7d70-b520-41ef-440f-a4a846f80880
  sha: d8e36831c3c94bb58be34dd544f44a6c6cb88568
libsnmp/libperl5.18_5.18.2-2ubuntu1.3_amd64.deb:
  size: 1326
  object_id: 1c6b35d8-5230-4f1b-7dc6-4ae008dee6b7
  sha: de1854a46271e04e79ca632928dbbf090f956774
libsnmp/libsnmp-base_5.7.2~dfsg-8.1ubuntu3.1_all.deb:
  size: 203322
  object_id: 7a3e0187-c447-4e5d-46a3-12d5020bc6e8
  sha: 142b0f5a913ae2c46da0c10030e7b1786b3294d2
libsnmp/libsnmp30_5.7.2~dfsg-8.1ubuntu3.1_amd64.deb:
  size: 787350
  object_id: ce9144b5-ceeb-462e-4cc8-c8b87e35cd75
  sha: 6532a6ec10a3b50bb676df27011ab7421bd95333
libsnmp/perl-base_5.18.2-2ubuntu1.3_amd64.deb:
  size: 1149076
  object_id: bc8667ca-c74e-4cdf-7846-87b01e030d36
  sha: 7356c1dd7da3c31c683c4d1ac7e9558e6f1b6e67
mongodb/mongodb-linux-x86_64-3.6.0.tgz:
  size: 86660499
  object_id: 14afcb04-bf44-49ff-72d0-6fbd32d388f9
  sha: 628ed70f49325ff017d179b67581b1eabc5eb446
